Repository Lands-Horizon-Corp/horizon-corp, pull requests merged in 2024-10, with the labels that each got.

#12 HCOP-10 enhancement of (forms,img,navs)
  client/public/e-coop-logo-1.png
  client/public/e-coop-logo-1.webp
  client/public/e-coop-logo-black.png
  client/public/e-coop-logo-black.webp
  client/public/e-coop-logo-white.png
  client/public/e-coop-logo-white.webp
  client/src/components/ecoop-logo.tsx
  client/src/components/footers/auth-footer.tsx
  client/src/components/footers/landing-footer/index.tsx
  client/src/components/navbars/auth-nav/index.tsx
  client/src/components/navbars/landing-nav/index.tsx
  client/src/components/navbars/nav-auth-contents.tsx
  client/src/components/navbars/root-nav.tsx
  client/src/components/providers/theme-provider.tsx
  client/src/components/sidebar/index.tsx
  client/src/modules/auth/components/account-cancelled.tsx
  client/src/modules/auth/components/auth-navbar.tsx
  client/src/modules/auth/components/auth-page-wrapper.tsx
  client/src/modules/auth/components/form-error-message.tsx
  client/src/modules/auth/components/forms/sign-in-form.tsx
  client/src/modules/auth/components/forms/sign-up-form.tsx
  client/src/modules/auth/components/verify-root/index.tsx
  client/src/modules/auth/layout.tsx
  client/src/modules/auth/pages/verify.tsx
  client/src/modules/landing/layout.tsx
  client/src/modules/landing/pages/_components/navbar/index.tsx
Labels: enhancement

#17 feat: Added cookie consent alert
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/cookie-consent.tsx
  client/src/components/icons.ts
  client/src/components/icons.tsx
  client/src/components/ui/alert.tsx
  client/src/modules/root-layout.tsx
Labels: feature

#20 Feature/hb 02 upload
  client/src/assets/images/file-thumbnails/attachment-audio.svg
  client/src/assets/images/file-thumbnails/attachment-doc.svg
  client/src/assets/images/file-thumbnails/attachment-pdf.svg
  client/src/assets/images/file-thumbnails/attachment-sheet.svg
  client/src/assets/images/file-thumbnails/attachment-txt.svg
  client/src/assets/images/file-thumbnails/attachment-video.svg
  client/src/horizon-corp/request/server.ts
  client/src/horizon-corp/server/common/ContactService.ts
  client/src/horizon-corp/server/common/FeedbackService.ts
  client/src/horizon-corp/server/common/GenderService.ts
  client/src/horizon-corp/server/common/MediaService.ts
  client/src/horizon-corp/server/common/RolesService.ts
  client/src/horizon-corp/server/common/index.ts
  client/src/horizon-corp/types/index.ts
  client/src/horizon-corp/types/media/index.ts
  client/src/horizon-corp/types/media/request.ts
  client/src/horizon-corp/types/media/response.ts
  client/src/modules/test/layout.tsx
  client/src/modules/test/pages/upload.tsx
  client/src/modules/test/route.ts
  client/src/root-route.tsx
  migration/sql/V6__create_media_table.sql
  server/go.mod
  server/go.sum
  server/internal/controllers/contact_controller.go
  server/internal/controllers/error_details_controller.go
  server/internal/controllers/gender_controller.go
  server/internal/controllers/media_controller.go
  server/internal/controllers/roles_controller.go
  server/internal/models/media.go
  server/internal/repositories/media_repository.go
  server/internal/requests/contact_request.go
  server/internal/requests/feedback_request.go
  server/internal/requests/media_request.go
  server/internal/requests/roles_request.go
  server/internal/resources/contact_resource.go
  server/internal/resources/error_details_resource.go
  server/internal/resources/feedback_resource.go
  server/internal/resources/gender_resource.go
  server/internal/resources/media_resource.go
  server/internal/resources/roles_resource.go
  server/internal/routes/routes.go
  server/main.go
  server/storage/media_storage.go
  server/storage/meida_helpers.go
  server/tmp/build-errors.log
Labels: bug, documentation, enhancement, feature, fixes, dependencies

#22 fix: Replace react-cookie with js-cookie package
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/cookie-consent.tsx
Labels: bug, fixes

#21 HCOP-14: time in time out
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/icons.tsx
  client/src/components/loader/loading-circle.tsx
  client/src/components/navbars/root-nav.tsx
  client/src/components/sidebar/index.tsx
  client/src/components/sidebar/sidebar-user-bar.tsx
  client/src/components/time-in-out/index.tsx
  client/src/components/time-in-out/realtime-time-text.tsx
  client/src/components/time-in-out/time-in-bar.tsx
  client/src/components/time-in-out/time-in-counter.tsx
  client/src/components/time-in-out/utils.ts
  client/src/components/time-in-out/utils.unit.test.ts
  client/src/components/webcam/camera-device-picker.tsx
  client/src/components/webcam/index.tsx
  client/src/components/webcam/use-camera-devices.tsx
  client/src/components/webcam/use-camera-grant.tsx
  client/src/constants/quoutes.tsx
  client/src/modules/admin/components/admin-navbar.tsx
  client/src/modules/admin/components/admin-sidebar.tsx
  client/src/modules/admin/layout.tsx
  client/src/modules/employee/components/employee-navbar.tsx
  client/src/modules/employee/components/employee-sidebar.tsx
  client/src/modules/employee/layout.tsx
  client/src/styles/index.css
  client/src/utils/index.ts
Labels: feature

#33 fix: Fix skipping not able to update store state
  client/src/modules/auth/components/verify-root/index.tsx
Labels: fixes

#34 HCOP-20: Final auth enhancements
  client/src/components/navbars/auth-nav/nav-auth-contents.tsx
  client/src/components/sidebar/sidebar-expand-context.ts
  client/src/components/sidebar/sidebar-user-bar.tsx
  client/src/helpers/cryptography.ts
  client/src/helpers/error-message-extractor/index.ts
  client/src/helpers/index.ts
  client/src/hooks/use-fetch-current-user.ts
  client/src/horizon-corp/server/auth/ProfileService.ts
  client/src/horizon-corp/server/auth/UserService.ts
  client/src/horizon-corp/types/auth/request.ts
  client/src/manager/environment-manager.ts
  client/src/manager/index.ts
  client/src/modules/auth/components/forms/sign-in-form.tsx
  client/src/modules/auth/pages/verify.tsx
  client/src/modules/auth/route.tsx
  client/src/modules/auth/validations/page-search.ts
  client/src/modules/root-layout.tsx
  client/src/store/user-auth-store.ts
Labels: enhancement, fixes

#38 chore: Enhanced navbars
  client/public/profile-cover.webp
  client/src/app.tsx
  client/src/components/nav/nav-components/nav-auth-group.tsx
  client/src/components/nav/nav-components/nav-ecoop-logo.tsx
  client/src/components/nav/nav-components/nav-get-started.tsx
  client/src/components/nav/nav-components/nav-profile-menu.tsx
  client/src/components/nav/nav-components/nav-sign-in.tsx
  client/src/components/nav/nav-components/nav-sign-out.tsx
  client/src/components/nav/nav-components/nav-sign-up.tsx
  client/src/components/nav/nav-components/nav-theme-toggle.tsx
  client/src/components/nav/nav-components/nav-time-in-bar.tsx
  client/src/components/nav/nav-container.tsx
  client/src/components/nav/navs/auth-nav.tsx
  client/src/components/nav/navs/landing-nav.tsx
  client/src/components/nav/navs/user-nav.tsx
  client/src/components/nav/root-nav.tsx
  client/src/components/navbars/auth-nav/index.tsx
  client/src/components/navbars/auth-nav/nav-auth-contents.tsx
  client/src/components/navbars/landing-nav/index.tsx
  client/src/components/navbars/root-nav.tsx
  client/src/components/theme-toggle/theme-toggle-menu.tsx
  client/src/components/time-in-out/index.tsx
  client/src/components/time-in-out/time-in-counter.tsx
  client/src/modules/admin/components/admin-navbar.tsx
  client/src/modules/admin/layout.tsx
  client/src/modules/auth/components/forms/forgot-password-email.tsx
  client/src/modules/auth/components/forms/reset-password-form.tsx
  client/src/modules/auth/layout.tsx
  client/src/modules/auth/pages/password-reset.tsx
  client/src/modules/employee/components/employee-navbar.tsx
  client/src/modules/employee/layout.tsx
  client/src/modules/landing/layout.tsx
  client/src/modules/member/layout.tsx
  client/tsconfig.app.tsbuildinfo
Labels: enhancement, fixes

#39 fix: Add workaround fix for web camera component
  client/src/components/icons.tsx
  client/src/components/nav/nav-components/nav-profile-menu.tsx
  client/src/components/nav/nav-components/nav-time-in-bar.tsx
  client/src/components/nav/navs/auth-nav.tsx
  client/src/components/time-in-out/index.tsx
  client/src/components/webcam/camera-device-picker.tsx
  client/src/components/webcam/index.tsx
  client/src/components/webcam/use-camera-devices.tsx
  client/src/components/webcam/use-camera-grant.tsx
Labels: fixes

#46 HCOP-41:feature/ Contact number enhancement
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/contact-input/contact-input.tsx
  client/src/components/ui/command.tsx
  client/src/modules/landing/pages/contact.tsx
  client/src/modules/landing/validations/contact-form.ts
  client/tsconfig.app.tsbuildinfo
Labels: enhancement, feature

#45 HCOP-23:feature/maps with search
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/icons.tsx
  client/src/components/map/LayerControl.tsx
  client/src/components/map/index.tsx
  client/src/modules/test/layout.tsx
  client/src/store/map-store.ts
  client/src/types/custom-component/index.ts
  client/src/types/custom-component/map.ts
  client/tsconfig.app.tsbuildinfo
Labels: feature
